# Creative Space

In [2]:
import numpy as np
import pandas as pd

In [8]:
A = np.random.rand(2,3)
print(A)

[[0.46304224 0.90182733 0.04433211]
 [0.08076961 0.09566386 0.32866576]]


In [9]:
A[0,:]

array([0.46304224, 0.90182733, 0.04433211])

In [90]:
B = np.full((2,5), np.nan)

In [91]:
B[1,3] = 4
B[0,1] = 2
print(B)

[[nan  2. nan nan nan]
 [nan nan nan  4. nan]]


In [85]:
np.count_nonzero(B)

2

In [97]:
np.isnan(B[0,0])

True

In [73]:
np.nanmean(B)

3.0

In [74]:
np.nan_to_num(B, copy=False, nan=0)

array([[0., 2., 0., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [75]:
np.putmask(B[:,0],B[:,0] == 0, 9)
print(B)

[[9. 2. 0. 0. 0.]
 [9. 0. 0. 4. 0.]]


In [53]:
B[B[0,:] == 9] = 0

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 5

In [89]:
x=np.arange(6).reshape(2,3)
y=x.copy()
z=x[1,:]+y[1,:]
print(x)
print(z)

[[0 1 2]
 [3 4 5]]
[ 6  8 10]
